# Russian translations file for port-utils program
# Copyright (C) 2021 Michail Krasnov <linuxoid85@gmail.com>
# This file is distributed under the same license as the PACKAGE package.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: 0.2\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-08-29 01:20+0300\n"
"PO-Revision-Date: 2021-08-28 HO:MI+ZONE\n"
"Last-Translator: Michail Krasnov <linuxoid85@gmail.com>\n"
"Language-Team: Calmira Locaize Team <linuxoid85@gmail.com>\n"
"Language: ru_RU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: port-utils.py:53
msgid "Error: you must run this script as root!"
msgstr "Ошибка: вы должны запустить этот скрипт от root!"

#: port-utils.py:58
msgid "The executable Port module must not be imported."
msgstr "Исполняемый файл Порта не может быть импортирован."

#: port-utils.py:139
msgid "Error: unknown operating mode "
msgstr "Ошибка: неизвестный режим работы "

#: port-utils.py:160
#, python-brace-format
msgid "Directory {0} exists."
msgstr "Директория {0} существует."

#: port-utils.py:162
msgid "Directory {} does not exist, creating a new one."
msgstr "Директория {} не существует, создаётся новая."

#: port-utils.py:167
msgid "Directory /var/cache/ports exists."
msgstr "Директория /var/cache/ports существует."

#: port-utils.py:169
msgid "Directory /var/cache/ports does not exist, creating a new one"
msgstr "Директории /var/cache/ports не существует, создаю новую"

#: port-utils.py:184
msgid ""
"Error: the file with distribution data does not exist, or there is no access "
"to read it. Exit."
msgstr ""
"Ошибка: файла с данными дистрибутива не существует, либо нет доступа для его "
"чтения. Выход."

#: port-utils.py:213
msgid "The previous version of ports is installed. Removed..."
msgstr "Предыдущая версия портов установлена. Удаляется..."

#: port-utils.py:216 port-utils.py:299
msgid "No previous ports were found."
msgstr "Предыдущих версий портов не установлено."

#: port-utils.py:221
msgid ""
"The previous version of the archive with ports was found in the cache. "
"Removed ..."
msgstr "Предыдущая версия архива с портами найдена в кеше. Удаляется..."

#: port-utils.py:224
msgid "No previous version of the ports system was found."
msgstr "Предыдущей версии системы портов не обнаружено."

#: port-utils.py:245 port-utils.py:398
#, python-brace-format
msgid "Error! Branch {0} does not exist!"
msgstr "Ошибка! Ветки {0} не существует!"

#: port-utils.py:253
msgid "Downloaded successfully!"
msgstr "Скачивание успешно!"

#: port-utils.py:255
msgid "The file has not been downloaded! Check internet access."
msgstr "Файл не был скачан! Проверьте доступ в интернет."

#: port-utils.py:269
msgid "Package unpacked successfully."
msgstr "Успешно распакован пакет."

#: port-utils.py:271
msgid "Unknown error, crash."
msgstr "Неизвестная ошибка, сбой в работе."

#: port-utils.py:275
msgid "Package read error. Perhaps he is broken."
msgstr "Ошибка чтения пакета. Возможно, он битый."

#: port-utils.py:279
msgid "Package unpacking error. The format is not supported."
msgstr "Ошибка распаковки пакета. Формат не поддерживается."

#: port-utils.py:282
msgid ""
"Package unpacking error. Package not found. It may not have been downloaded, "
"or a third-party program changed it's name during unpacking."
msgstr ""
"Ошибка распаковки пакета. Пакет не существует. Возможно, он не был скачан, "
"либо был удалён сторонней программой во время распаковки."

#: port-utils.py:289
msgid "Directory with unpacked ports found, installing..."
msgstr "Директория с распакованными портами найдена, устанавливается."

#: port-utils.py:291
msgid "Package unpacking error: directory not found."
msgstr "Ошибка распаковки пакета: распакованная директория не найдена."

#: port-utils.py:296
msgid "Found directory with previous ports version. Removed..."
msgstr "Найдена директория с предыдущей версией портов. Удаляется..."

#: port-utils.py:316
#, python-brace-format
msgid "Directory {0} is exist"
msgstr "Директория {0} существует"

#: port-utils.py:319
#, python-brace-format
msgid "Error: the required directory {0} does not exist!"
msgstr "Ошибка: необходимой директории {0} не существует!"

#: port-utils.py:324
#, python-brace-format
msgid "Directory: file {0} is exist!"
msgstr "Директория: файл {0} существует!"

#: port-utils.py:327
#, python-brace-format
msgid "Directory {0} does not exist"
msgstr "Директория {0} не существует"

#: port-utils.py:331
#, python-brace-format
msgid "Error using checkFile: argument {0} for 'mode' does not exist!"
msgstr "Ошибка использования checkFile: аргумент {0} для 'mode' не существует!"

#: port-utils.py:338
msgid "Checking for cache existence..."
msgstr "Проверка наличия кеша..."

#: port-utils.py:340
msgid "OK"
msgstr "Успешно"

#: port-utils.py:345
msgid "FAIL: Cache directory not found"
msgstr "НЕУДАЧНО: Директории с кешем не существует"

#: port-utils.py:350
msgid "Checking for the existence of log files..."
msgstr "Проверка на наличие файлов лога"

#: port-utils.py:353
#, python-brace-format
msgid "File {0}: OK"
msgstr "Файл {0}: Успешно"

#: port-utils.py:356
#, python-brace-format
msgid "Error: the required file {0} does not exist!"
msgstr "Ошибка: необходимый файл {0} не существует!"

#: port-utils.py:361
#, python-brace-format
msgid "Error: the required file {0} has not been deleted!"
msgstr "Ошибка: необходимый файл {0} не может быть удалён!"

#: port-utils.py:364
#, python-brace-format
msgid "File {0} has deleted succesfully!"
msgstr "Файл {0} удалён успешно!"

#: port-utils.py:369
msgid "Checking for the existence of a source tree..."
msgstr "Проверка на наличие дерева исходного кода..."

#: port-utils.py:381
msgid "Error: the required /usr/src has not been deleted!"
msgstr "Ошибка: необходимая директория /usr/src не может быть удалена!"

#: port-utils.py:407
msgid "No such file /var/cache/ports/news.txt"
msgstr "Не существует файла /var/cache/ports/news.txt"

#: port-utils.py:434
msgid ""
"Error: the update-ports version is not compatible with the current Calmira "
"version!"
msgstr "Ошибка: версия port-utils не совместима с текущей версией Calmira!"

#: port-utils.py:462
msgid "Checking for correct update..."
msgstr "Проверка на корректное обновление..."

#: port-utils.py:467
msgid "NOT FOUND! It is possible that something went wrong during the update."
msgstr "НЕ СУЩЕСТВУЕТ! Возможно, во время обновления что-то пошло не так."

#: port-utils.py:431
msgid "Name: {}"
msgstr "Имя: {}"

#: port-utils.py:432
msgid "Version: {}"
msgstr "Версия: {}"

#: port-utils.py:433
msgid "Maintainer: {}"
msgstr "Сопровождающий: {}"

#: port-utils.py:434
msgid "Depends: {}"
msgstr "Зависимости^ {}"
